# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-12 13:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20151014_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='player1_points',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(33)]),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='player2_points',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(33)]),
        ),
    ]
