# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 10:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20151112_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('deadline', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.Tournament')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.Tournament'),
        ),
        migrations.AddField(
            model_name='group',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.Stage'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=set([('name', 'tournament')]),
        ),
    ]
