# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160701_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='next_stage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Stage'),
        ),
    ]
