# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 13:52
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Tournament = apps.get_model("core", "Tournament")
    Stage = apps.get_model("core", "Stage")
    for t in Tournament.objects.all():
        fake_stage = None
        for group in t.groups.all():
            if group.stage_id:
                continue
            fake_stage = fake_stage or Stage.objects.create(name="fake", deadline='2016-01-01', tournament=t)
            group.stage = fake_stage
            group.save()


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_stage_next_stage'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
