# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160701_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.Stage'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('name', 'stage')]),
        ),
    ]
