# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160701_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='started_at',
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='group',
            name='tournament',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('name',)]),
        ),
    ]
