# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20161129_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
